name: Node

on:
    push:
        branches:
            - main

jobs:
    
    Test:
        runs-on: self-hosted

        steps:
            - name: checkout Repo
              uses: actions/checkout@v2
            - name: Node install
              uses: actions/setup-node@v6
            - name: Start the process
              run: pm2 start "npm run dev"
            

    Deploy:
        runs-on: self-hosted
        needs: Test

      
            